version: '3'
services:

  wapi:
    image: wapi
    cap_add: 
      - SYS_ADMIN
    ports:
      - 3001:3001
    build: .
    volumes:
      - .:/app
      - wapi_files:/wapi_files
    environment:
      - DEBUG=express:*
      - ROCKETCHAT_URL=rocketchat:3000
      - TZ=America/Sao_Paulo
    command:
      #node /app/index.js
      #nodemon /app/index.js
      npm run dev
    depends_on:
      - rocketchat      

  rocketchat:
    image: rocketchat/rocket.chat:3.10.4
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - rocket_uploads:/app/uploads
    environment:
      - ADMIN_USERNAME=debug
      - ADMIN_PASS=debug
      - ADMIN_EMAIL=admin@example.com
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      #- MAIL_URL=smtp://mailhog
      - CREATE_TOKENS_FOR_USERS=true
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - rocket_db:/data/db
      - rocket_db_config:/data/configdb
      - rocket_db_dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:4.0
    command: 'bash -c "for i in `seq 1 30`; do mongo mongo/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})\" && s=$$? && break || s=$$?; echo \"Tried $$i times. Waiting 5 secs...\"; sleep 5; done; (exit $$s)"'
    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  wapi_files: {}
  rocket_uploads: {}
  rocket_db: {}
  rocket_db_config: {}
  rocket_db_dump: {}
    
