version: '3'
services:

  wapi:
    cap_add: 
      - SYS_ADMIN
    ports:
      - 3001:3001
    build: .
    volumes:
      - .:/app
      - wapi_files:/wapi_files
    env_file:
      - .env
    command:
      node /app/index.js

volumes:
  wapi_files: {}
    